### PR TITLE
[NEW] Additional poll modes

### LINKED ISSUE #10: [FEATURE] Additional Poll Modes Template
Currently the Poll App has two modes of poll creation - Multiple Choice and Single Choice. This implementation would extend these modes to the following types:
- 1- 5 Poll.
- 1-10 Poll.
- Agree/Disagree Poll.
- Overrated/Underrated Poll.
- Emoji Rank Poll

The benefit that these polls would provide to the users is that the users would get a template of poll options without having to fill them out themselves.

### 1 - 5 Poll

Additional Poll Types - 1 to 5 (1)

### Overrated/Underrated Poll

Additional Poll Types - Overrated-Underrated (1)

### Agree/Disagree Poll

Additional Poll Types - Agree-Disagree

### PR DESCRIPTION
**Pull request by RonLek**
- Adds `template` slash subcommand for trigerring Poll creation through templates.
- Creates Poll Template Modal with `StaticSelectElement` to select poll template.
- Adds Overrated/Underrated Poll (Options: Overrated, Appropriately Rated, Never Tried, Underrated).
- Adds 1-to-5 Poll (Options: 1 - 5)
- Adds 1-to-10 Poll (Options: 1 - 10)
- Adds Agree/Disagree Poll (Options - Agree, Disagree)
- Adds Emoji Rank Poll (Options - 🤩 Great, 🙂 Good, 😐 Neutral, 🙁 Bad, 😢 Awful)

https://user-images.githubusercontent.com/28918901/127742491-15073207-de51-4ad8-8fd4-ff99ea655e4e.mp4

Closes #10

### CODE REVIEW

**Comment by RonLek** [comment]
@murtaza98 @ramkumarkb Please take a look. Thanks.

**Comment by RonLek** [comment]
@murtaza98 Modified the `/poll template` flow and used interactivity directly for modifying the existing modal. Please take a look.

**Comment by murtaza98** [comment]
Getting [this](https://open.rocket.chat/group/poll-app-contributor?msg=J3yFxyoGJqHGSgXAB) issue in this PR

**Comment by murtaza98** [comment]
Hi, @RonLek I'm still getting this issue on the latest code for this branch. 

Issue:
- start a poll in multiple-choice questions mode and enter more than 2 options
- switch the mode to single-choice and notice only 2 options are visible. Ideally, it shouldn't hide any options. Please checkout the below clip for more info.

https://user-images.githubusercontent.com/34130764/132980064-40094a1b-3d3e-4cf4-8c12-bd2010d50b1e.mp4

**Comment by RonLek** [comment]
Thanks @murtaza98 . This one is still WIP.

**Comment by murtaza98** [comment]
> Thanks @murtaza98. This one is still WIP.

Hey @RonLek, I've came up with this simple solution for [this](https://github.com/RonLek/rocket.chat.app-poll/pull/1) PR. Feel free to review and merge it into this PR, or if you wish to implement any other solution, that's fine as well.

**Comment by RonLek** [comment]
That's awesome! Thanks @murtaza98 . I've made a few fixes within your PR. Let me know if I can proceed with merging your updated PR within this branch.

**Comment by murtaza98** [comment]
Hi, @RonLek Thanks for the fixes. The changes look good. Feel free to merge it into your main PR :smiley:

**Comment by RonLek** [comment]
Thanks @murtaza98 . Merged it in within this one.

**Comment by murtaza98** [comment]
Awesome Thanks!! This LGTM!!

**Review by murtaza98 — APPROVED** [review]

**Pull request merged**
